### ISSUE TITLE
Errors when running make

### ISSUE THREAD

**Issue by AdamCampbell** [jdiehl/async-network#12]
Output:
----------------------------
 
=== BUILD TARGET AsyncNetwork OF PROJECT AsyncNetwork WITH THE DEFAULT CONFIGURATION (Release) ===
** BUILD FAILED **

The following build commands failed:
	CompileC build/AsyncNetwork.build/Release/AsyncNetwork.build/Objects-normal/x86_64/GCDAsyncSocket.o ThirdParty/CocoaAsyncSocket/GCD/GCDAsyncSocket.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC build/AsyncNetwork.build/Release/AsyncNetwork.build/Objects-normal/x86_64/GCDAsyncUdpSocket.o ThirdParty/CocoaAsyncSocket/GCD/GCDAsyncUdpSocket.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)

=== BUILD TARGET AsyncNetworkIOS OF PROJECT AsyncNetwork WITH THE DEFAULT CONFIGURATION (Release) ===
** BUILD FAILED **

The following build commands failed:
	CompileC build/AsyncNetwork.build/Release-iphoneos/AsyncNetworkIOS.build/Objects-normal/armv7/GCDAsyncUdpSocket.o ThirdParty/CocoaAsyncSocket/GCD/GCDAsyncUdpSocket.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC build/AsyncNetwork.build/Release-iphoneos/AsyncNetworkIOS.build/Objects-normal/armv7/GCDAsyncSocket.o ThirdParty/CocoaAsyncSocket/GCD/GCDAsyncSocket.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)

=== BUILD TARGET AsyncNetworkIOS OF PROJECT AsyncNetwork WITH THE DEFAULT CONFIGURATION (Release) ===
** BUILD FAILED **

The following build commands failed:
	CompileC build/AsyncNetwork.build/Release-iphonesimulator/AsyncNetworkIOS.build/Objects-normal/i386/GCDAsyncSocket.o ThirdParty/CocoaAsyncSocket/GCD/GCDAsyncSocket.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC build/AsyncNetwork.build/Release-iphonesimulator/AsyncNetworkIOS.build/Objects-normal/i386/GCDAsyncUdpSocket.o ThirdParty/CocoaAsyncSocket/GCD/GCDAsyncUdpSocket.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)
cp: build/Release/AsyncNetwork.framework/AsyncNetwork: No such file or directory
cp: build/Release/AsyncNetwork.framework/Modules: No such file or directory
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: build/Release-iphoneos/AsyncNetworkIOS.framework/AsyncNetworkIOS (No such file or directory)

**Comment by jdiehl** [comment]
Did you initialize the git submodules as described in the readme?

```
git submodule init
git submodule update
```

**Comment by AdamCampbell** [comment]
You're right, I thought I did it but failed somehow. 
This framework has been really useful in getting an iPhone to talk to tvOS.
I intend to look into making this carthage compatible to simplify the installation.
Thanks for all your work on this :)

**Comment by jdiehl** [comment]
Thanks for the feedback! I have added these steps to make, to make it a little easier.
