### ISSUE TITLE
Building & Debugging

### ISSUE THREAD

**Issue by ggb88** [jdiehl/async-network#14]
Hello Jonathan,

I need a little help if possible with two things - running the examples and console debugging

- In regard to the former, I can successfully build the frameworks.  I have installed both frameworks into /Library/Frameworks, but when i try to compile an example in Xcode (such as ClientServer), it fails because 'AsyncNetwork/AsyncNetwork.h' cannot be found.  I've restarted Xcode (7.2) and tried re-adding the framework, but must be missing some other setting
- In regards to debugging, I'd like to enable the debugging that is in CocoAsyncSocket - what would be the best way to enable this and package a framework with debugging enabled.  A quick search of sync-network doesn't appear to have any console logging.  Is that right?

Thanks
Garry

**Comment by jdiehl** [comment]
Hi Garry,

the framework should be installed as an embedded framework, not a system framework:

1. Compile AsyncNetwork
2. Copy AsyncNetwork.framework into your project folder
3. In the project General Tab: Add the framework to Embedded Binaries and Linked Frameworks

This way the framework will be embedded in your application and run on any system.

Concerning your second question: I personally do not like console logging for debugging thus I have not included any such logs anywhere. To debug the framework, I typically include its sources and step through it with the debugger. You can, however, add log statements to your delegate methods.

Best
  Jonathan

**Comment by ggb88** [comment]
Hi Jonathan, thanks for such an expedient reply.  Got it all working, thanks for the tips.
