### ISSUE TITLE
hi pls can help me to set port and host

### ISSUE THREAD

**Issue by fredhartem** [jdiehl/async-network#23]
hi pls can help me to set port and host on client and server pls

**Comment by jdiehl** [comment]
You can set the port of the server by setting the port property of AsyncServer before calling start. 

You cannot set the port of the client as that is determined automatically via Bonjour. It should still work with a server with a custom port. 

If you need to connect by IP address and port, use AsyncConnection instead. Use the connectionWithHost:port: method.
