### ISSUE TITLE
'GCDAsyncSocket.h' file not found

### ISSUE THREAD

**Issue by zachgibson** [jdiehl/async-network#24]
Seems CocoaAsyncSocket files are missing. I’ve compiled using the makefile and added the framework to the project folder and Embedded Binaries and Linked Frameworks and Libraries. Running the project results in *'GCDAsyncSocket.h' file not found*. Not sure what I’m missing.

**Comment by jdiehl** [comment]
I made the socket headers public. Please pull the latest version from master and try again (start with make).

**Comment by zachgibson** [comment]
Thanks for the quick response @jdiehl! Fresh clone, running make, then following the steps in the README worked.
