### ISSUE TITLE
AysncServer's sendCommand Does Not Work in AsyncNetworkIOS.framework

### ISSUE THREAD

**Issue by willSapgreen** [jdiehl/async-network#4]
Hello Jonathan,
It seems that in AsyncNetworkIOS.framework AsyncServer's sendCommand doesn't work. It sounds weird because in ClientServer example, AsyncNetServer's sendCommand works, which uses AsyncNetwork.framework. Would you mind to confirm this potential issue? At same time I will keep testing and update if any new evidence. Please let me know if any problem. Thank you so much for helping.

**Comment by jdiehl** [comment]
It works like a charm for me. Even when replacing the sendObject: call with sendCommand: and reporting the command in the server output, it still works. I am guessing the error lies somewhere else. Please provide some more insights so we can get to the bottom of this:

* Are you including the source files or the framework?
* Did you run the `make` file to build the framework or did you compile it by hand? 
* Can you post the lines that touch the framework?

**Comment by willSapgreen** [comment]
Hello Jonathan,
Thanks for the quick response. Do you use Mac framework or IOS framework to
test the server side? Mac framework works on my side too but not IOS
framework. However, I may miss something in my implementation. So I will do
more experiment and give you an update.


   - Are you including the source files or the framework? A: IOS framework
   - Did you run the make file to build the framework or did you compile it
   by hand? A: compile by hand
   - Can you post the lines that touch the framework? A: What does "the
   lines" mean? Sorry for my limited knowledge.

Thank you so much for helping.

**Comment by willSapgreen** [comment]
Hello Jonathan,
it turns out I made a silly mistake. In the AsyncClient delegate, I only implement

- (void)client:(AsyncClient *)theClient didReceiveCommand:(AsyncCommand)command object:(id)object connection:(AsyncConnection *)connection responseBlock:(AsyncNetworkResponseBlock)block

but the server side uses sendCommand:object.

After implementing - (void)client:(AsyncClient *)theClient didReceiveCommand:(AsyncCommand)command object:(id)object connection:(AsyncConnection *)connection;

the AsyncClient's delegate can receive the command and object.

Thank you so much for helping.
