### ISSUE TITLE
Feature - Individual sendCommand in AsyncServer and AsyncClient

### ISSUE THREAD

**Issue by willSapgreen** [jdiehl/async-network#7]
Hello Jason,

In AsyncServer and AsyncClient, sendCommand method will send object to all connected AsyncConnections.

Is it possible to send object to specific AsyncConnection? For example, the API will look like

- (void)sendCommand:(AsyncCommand)command
             object:(id<NSCoding>)object
      responseBlock:(AsyncNetworkResponseBlock)block
       toConnection:(AsyncConnection*)connection;

With your permission, I can write this method and you can review it.

P.S. I don't know if there is a "Feature" to create in Github. So I use "Issues" instead. Sorry for any inconvenience.

**Comment by jdiehl** [comment]
If you have the connection object, you can use the method `sendCommand:object:` directly on that connection object. The client doesn't need to know ;)

**Comment by willSapgreen** [comment]
Thank you for the quick response.
In sendCommand:object:responseBlock method, the command and object will be sent to all connections. 
In my understanding, the object is the data you want to send, not the connection(AsyncConnection).
So if there are multiple connections, how to send the command and the object to the specific one in those connections.
Sorry my previous description is unclear.

**Comment by jdiehl** [comment]
The connection object also has this method, allowing you to send something to one specific host.

**Comment by willSapgreen** [comment]
Hello Jason,
Finally I may know what you are talking about. Is the "connection object" you mentioned is NSMutableSet *connections in either AsyncClient or AsyncServer? So I can use the AsyncConnection in connections to send something to one specific host/client.
Thank you for helping.
