### ISSUE TITLE
Feature: Add to CocoaPods

### ISSUE THREAD

**Issue by Schemetrical** [jdiehl/async-network#8]
Would be great if the framework was made available on CocoaPods :-)

**Comment by jdiehl** [comment]
I have no experience with CocoaPods. If you are willing to implement the support and it does not break the regular deployment process, I will be happy to merge a pull request.

**Comment by Schemetrical** [comment]
Awesome, I'll try to get it going. This is a really great framework and it would be really nice to get it on CocoaPods to integrate with other projects easily.

**Comment by Schemetrical** [comment]
Do you have an email or some IM client to communicate with (other than this GitHub issue thread)? It would be great to have some information on versions and other stuff for the podspec.

**Comment by jdiehl** [comment]
Not really, sorry. The build is currently done via the make script, which compiles all 2 versions of the framework (iOS and Mac) and places them in a DMG for deployment.

**Comment by Schemetrical** [comment]
So far the pods works, but the pod needs to be pushed to the repo before it passes `pod spec lint` and goes into the cocoapod trunk. I'll try to find a way to test without it actually being on the repo, but if else fails, I might have to submit the PR and get it pulled first before I can submit to the cocoapod trunk.

**Comment by jdiehl** [comment]
Let me know, if I need to do anything!

**Comment by rjgdesign** [comment]
+1

**Comment by willSapgreen** [comment]
+2

**Comment by ggb88** [comment]
+3

**Comment by jdiehl** [comment]
Done, please let me know if it works for you guys

**Comment by ggb88** [comment]
Hi Jonathan, I've incorporated the pod into my project successfully.  Thank you to all concerned.  One suggestion I would make is that async-network seems to include in the POD those components of CocoaAsyncSocket that it depends on rather than requiring CocoaAsyncSocket being a dependency named in the async pod spec.  Could this be done?

**Comment by Schemetrical** [comment]
+1 ^

**Comment by jdiehl** [comment]
I tried that to no avail: It would break the way the framework is compiled manually.

**Comment by Schemetrical** [comment]
I think its worth it to break manual compilation. Cocoapods are much more efficient and they generate the appropriate libraries needed to be implemented in projects. Its probably more widely used than compiling the framework manually.

**Comment by jdiehl** [comment]
I disagree. I don't like Cocoapods very much (they are extremely slow and create weird project structures), and I don't want to force people to use it. Carthage, however, might be a better approach to manually compiling the framework that might be compatible with how dependencies work in Cocoapods.

**Comment by jdiehl** [comment]
@levey fixed the dependencies in his pull request, thanks!
