### ISSUE TITLE
AsyncClient Connection Error

### ISSUE THREAD

**Issue by willSapgreen** [jdiehl/async-network#9]
When setting autoConnect to TRUE in AsyncClient and start,

- (void)client:(AsyncClient *)theClient didFailWithError:(NSError *)error will be called.

The error is "Connection refused".

This only happens when the server does not exist.

Is it normal situation?

Thank you.

**Comment by jdiehl** [comment]
Sorry for the late answer. I just tested this with the ClientServer example and cannot reproduce the issue: when starting a client with autoConnect TRUE and no server, the error method is not called.

The described behaviour could happen, if a Bonjour service on your networking is advertising an async-server but there is no server listening on the advertised port.
